export const SET_SELECTED_TOPIC = "SET_SELECTED_TOPIC";
export const SET_IS_TOPIC_OPEN = "SET_IS_TOPIC_OPEN";
export const SET_OPTION_SWITCH = "SET_OPTION_SWITCH";
export const SET_IS_CLICKED = "SET_IS_CLICKED";
export const SET_NOW_LOGIN = "SET_NOW_LOGIN";
